<?php

return [
    'faculte' => [
        'title' => 'Année faculté — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'Année faculté',
        'subtitle' => 'Decouverte du web, JavaScript et PHP',
        'sectionLabel' => 'Projets',
        'cards' => [
            [
                'href' => 'project.php?slug=cv',
                'iconClass' => 'purple',
                'icon' => 'fas fa-file-alt',
                'title' => 'Curriculum Vitae HTML',
                'description' => 'CV réalisé entierement en HTML/CSS en 2023.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                ],
            ],
            [
                'href' => 'project.php?slug=balisephp',
                'iconClass' => 'green',
                'icon' => 'fas fa-question-circle',
                'title' => 'Quizz avec PHP',
                'description' => 'Application de quizz interactif, première utilisation de PHP cote serveur.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'JavaScript'],
                    ['class' => 'amber', 'label' => 'PHP'],
                ],
            ],
            [
                'href' => 'project.php?slug=balisehtml',
                'iconClass' => 'teal',
                'icon' => 'fas fa-tag',
                'title' => 'Les balises HTML',
                'description' => 'Exploration et apprentissage des differentes balises HTML.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                ],
            ],
            [
                'href' => 'project.php?slug=experience',
                'iconClass' => 'purple',
                'icon' => 'fas fa-car',
                'title' => 'Assistant de Conduite',
                'description' => 'Mini-projet JavaScript : assistant d\'experience de conduite interactif.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'blue', 'label' => 'JavaScript'],
                ],
            ],
            [
                'href' => 'project.php?slug=fizzbuzz',
                'iconClass' => 'teal',
                'icon' => 'fas fa-calculator',
                'title' => 'FizzBuzz',
                'description' => 'Projet FizzBuzz en C.',
                'tags' => [
                    ['class' => 'amber', 'label' => 'C'],
                ],
            ],
            [
                'href' => 'project.php?slug=mastermind',
                'iconClass' => 'pink',
                'icon' => 'fas fa-dice-four',
                'title' => 'Mastermind',
                'description' => 'Projet Mastermind en C.',
                'tags' => [
                    ['class' => 'amber', 'label' => 'C'],
                ],
            ],
        ],
    ],
    'deuxieme' => [
        'title' => 'Deuxième année — Justine Hannauer',
        'badge' => 'Deuxième année',
        'heading' => 'Deuxième année de BUT',
        'subtitle' => 'Decouverte du web, JavaScript et PHP',
        'sectionLabel' => 'Projets',
        'cards' => [
            [
                'href' => 'project.php?slug=vitrine',
                'iconClass' => 'purple',
                'icon' => 'fas fa-file',
                'title' => 'Illustrations',
                'description' => 'Outils utilises : Figma et InDesign.',
                'tags' => [
                    ['class' => 'green', 'label' => 'Figma'],
                    ['class' => 'green', 'label' => 'InDesign'],
                    ['class' => 'green', 'label' => 'Illustrator'],
                ],
            ],
            [
                'href' => 'project.php?slug=htmlcover',
                'iconClass' => 'green',
                'icon' => 'fas fa-hourglass-start',
                'title' => 'Première utilisation de Bootstrap',
                'description' => 'Premiers pas avec le framework Bootstrap.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'purple', 'label' => 'Bootstrap'],
                ],
            ],
            [
                'href' => 'project.php?slug=tutorat',
                'iconClass' => 'teal',
                'icon' => 'fas fa-desktop',
                'title' => 'Reproduction d\'une maquette',
                'description' => 'Reproduction d\'une maquette fournie en HTML/CSS.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'pink', 'label' => 'Figma'],
                ],
            ],
            [
                'href' => 'project.php?slug=sae301',
                'iconClass' => 'amber',
                'icon' => 'fas fa-plane',
                'title' => 'Projet SAE301 Clay',
                'description' => 'Projet de gestion d\'un site web pour la vente d\'avions.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'amber', 'label' => 'PHP'],
                    ['class' => 'amber', 'label' => 'SQLite'],
                    ['class' => 'purple', 'label' => 'Twig'],
                    ['class' => 'green', 'label' => 'Figma'],
                    ['class' => 'teal', 'label' => 'UX'],
                    ['class' => 'pink', 'label' => 'Methode Agile'],
                    ['class' => 'pink', 'label' => 'Scrum'],
                    ['class' => 'pink', 'label' => 'Trello'],
                ],
            ],
            [
                'href' => 'project.php?slug=clay',
                'iconClass' => 'purple',
                'icon' => 'fas fa-jet-fighter',
                'title' => 'Projet Clay',
                'description' => 'Refonte d\'un site web pour la vente d\'avions.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'amber', 'label' => 'SQLite'],
                    ['class' => 'purple', 'label' => 'Symfony'],
                    ['class' => 'purple', 'label' => 'Twig'],
                ],
            ],
            [
                'href' => 'project.php?slug=sae401',
                'iconClass' => 'purple',
                'icon' => 'fas fa-water',
                'title' => 'Projet SAE401',
                'description' => 'Decrypt\'eau : jeu pour apprendre le cycle de l\'eau.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'blue', 'label' => 'JavaScript'],
                    ['class' => 'amber', 'label' => 'MySQL'],
                    ['class' => 'purple', 'label' => 'Symfony'],
                    ['class' => 'purple', 'label' => 'Twig'],
                    ['class' => 'green', 'label' => 'Figma'],
                    ['class' => 'pink', 'label' => 'Methode Agile'],
                    ['class' => 'pink', 'label' => 'Scrum'],
                    ['class' => 'pink', 'label' => 'Trello'],
                ],
            ],
            [
                'href' => 'project.php?slug=sae402',
                'iconClass' => 'purple',
                'icon' => 'fas fa-bugs',
                'title' => 'Projet SAE402',
                'description' => 'Projet d\'un petit jeu video sur un papillon.',
                'tags' => [
                    ['class' => 'teal', 'label' => 'Unity'],
                    ['class' => 'green', 'label' => 'Blender'],
                    ['class' => 'amber', 'label' => 'C#'],
                    ['class' => 'pink', 'label' => 'Methode Agile'],
                ],
            ],
        ],
    ],
    'troisieme' => [
        'title' => 'Troisième année — Justine Hannauer',
        'badge' => 'Troisième année',
        'heading' => 'Troisième année',
        'subtitle' => 'Laravel, gestion de projet agile et design',
        'sectionLabel' => 'Projets',
        'cards' => [
            [
                'href' => 'project.php?slug=accessibilite',
                'iconClass' => 'amber',
                'icon' => 'fas fa-universal-access',
                'title' => 'Site web accessible',
                'description' => 'Création d\'un site web accessible, respectant les normes WCAG.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'purple', 'label' => 'Tailwind CSS'],
                    ['class' => 'pink', 'label' => 'Accessibilité'],
                    ['class' => 'pink', 'label' => 'Gestion de projet'],
                    ['class' => 'pink', 'label' => 'Trello'],
                ],
            ],
            [
                'href' => 'project.php?slug=jirlo',
                'iconClass' => 'purple',
                'icon' => 'fas fa-map-pin',
                'title' => 'Projet Jirlo',
                'description' => 'Application de gestion de projet agile developpée avec Laravel.',
                'tags' => [
                    ['class' => 'amber', 'label' => 'SQLite'],
                    ['class' => 'purple', 'label' => 'Laravel'],
                    ['class' => 'purple', 'label' => 'Tailwind CSS'],
                    ['class' => 'green', 'label' => 'Figma'],
                    ['class' => 'teal', 'label' => 'UX'],
                    ['class' => 'pink', 'label' => 'Trello'],
                    ['class' => 'pink', 'label' => 'Miro'],
                    ['class' => 'pink', 'label' => 'Cahier des charges'],
                ],
            ],
            [
                'href' => 'project.php?slug=chocolat',
                'iconClass' => 'amber',
                'icon' => 'fas fa-cookie-bite',
                'title' => 'L\'Usine Chocolat',
                'description' => 'Application web pour une usine de chocolat, avec Laravel et Agile.',
                'tags' => [
                    ['class' => 'amber', 'label' => 'SQLite'],
                    ['class' => 'purple', 'label' => 'Laravel'],
                    ['class' => 'purple', 'label' => 'Tailwind CSS'],
                    ['class' => 'green', 'label' => 'Figma'],
                    ['class' => 'teal', 'label' => 'UX'],
                    ['class' => 'pink', 'label' => 'Agile'],
                    ['class' => 'pink', 'label' => 'Trello'],
                    ['class' => 'pink', 'label' => 'Cahier des charges'],
                    ['class' => 'pink', 'label' => 'Miro'],
                ],
            ],
            [
                'href' => 'project.php?slug=di5',
                'iconClass' => 'amber',
                'icon' => 'fas fa-mobile-alt',
                'title' => 'Application mobile',
                'description' => 'Application mobile pour trouver des cinemas et acheter des billets.',
                'tags' => [
                    ['class' => 'teal', 'label' => 'Android Studio'],
                    ['class' => 'amber', 'label' => 'Kotlin'],
                    ['class' => 'pink', 'label' => 'Gestion de projet'],
                ],
            ],
            [
                'href' => 'project.php?slug=visu',
                'iconClass' => 'amber',
                'icon' => 'fas fa-cube',
                'title' => 'Projet visualisation 3D',
                'description' => 'Réalisation de visualisations 3D d\'un musée d\'art.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'JavaScript'],
                    ['class' => 'purple', 'label' => 'Three.js'],
                    ['class' => 'coral', 'label' => '3D'],
                ],
            ],
            [
                'href' => 'project.php?slug=ad',
                'iconClass' => 'amber',
                'icon' => 'fas fa-globe',
                'title' => 'Refonte du site d\'Alsace Digitale',
                'description' => 'Site vitrine pour retrouver évènements et communautes.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'amber', 'label' => 'Strapi'],
                    ['class' => 'purple', 'label' => 'VueJS'],
                    ['class' => 'purple', 'label' => 'NuxtJS'],
                    ['class' => 'pink', 'label' => 'Scrum'],
                    ['class' => 'pink', 'label' => 'Trello'],
                ],
            ],
            [
                'href' => 'project.php?slug=spa',
                'iconClass' => 'amber',
                'icon' => 'fas fa-home',
                'title' => 'Refonte du site de la SPA Strasbourg',
                'description' => 'Refonte pour mieux informer et faciliter adoptions et benevolat.',
                'tags' => [
                    ['class' => 'blue', 'label' => 'HTML'],
                    ['class' => 'blue', 'label' => 'CSS'],
                    ['class' => 'blue', 'label' => 'JavaScript'],
                    ['class' => 'amber', 'label' => 'PHP'],
                    ['class' => 'orange', 'label' => 'WordPress'],
                    ['class' => 'pink', 'label' => 'Miro'],
                    ['class' => 'pink', 'label' => 'Trello'],
                    ['class' => 'pink', 'label' => 'Cahier des charges'],
                    ['class' => 'pink', 'label' => 'Question et tests utilisateurs'],
                    ['class' => 'green', 'label' => 'Figma'],
                    ['class' => 'green', 'label' => 'Canva'],
                    ['class' => 'green', 'label' => 'DaVinci Resolve'],
                    ['class' => 'teal', 'label' => 'UX'],
                ],
            ],
            [
                'href' => 'project.php?slug=di6',
                'iconClass' => 'amber',
                'icon' => 'fas fa-gamepad',
                'title' => 'Projets Unity et IA',
                'description' => 'Jeux, réalite virtuelle/augmentee et IA generative.',
                'tags' => [
                    ['class' => 'teal', 'label' => 'Unity'],
                    ['class' => 'amber', 'label' => 'C#'],
                    ['class' => 'amber', 'label' => 'Python'],
                    ['class' => 'coral', 'label' => 'Réalite virtuelle'],
                    ['class' => 'coral', 'label' => 'Réalite augmentee'],
                    ['class' => 'coral', 'label' => 'IA generative'],
                    ['class' => 'coral', 'label' => '3D'],
                ],
            ],
        ],
    ],
];
