<?php

return [
    'lycee' => [
        'title' => 'Premier site — Justine Hannauer',
        'badge' => 'lycee',
        'heading' => 'Premier site — Justine Hannauer',
        'subtitle' => 'Projets et travaux realisés en HTML et CSS.',
        'summary' => 'Premier projet web, découverte du HTML et du CSS.',
        'parentPageSlug' => '',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'amber', 'label' => 'Python'],
        ],
    ],
    'cv' => [
        'title' => 'Curriculum Vitae HTML — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'Curriculum Vitae HTML',
        'subtitle' => 'Premier CV en HTML/CSS.',
        'summary' => 'CV realise entierement en HTML et CSS pour apprendre les bases du web.',
        'parentPageSlug' => 'faculte',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
        ],
    ],
    'balisephp' => [
        'title' => 'Quizz avec PHP — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'Quizz avec PHP',
        'subtitle' => 'Première logique serveur en PHP.',
        'summary' => 'Petit quizz interactif pour decouvrir PHP cote serveur.',
        'parentPageSlug' => 'faculte',
        'tags' => [
            ['class' => 'blue', 'label' => 'JavaScript'],
            ['class' => 'amber', 'label' => 'PHP'],
        ],
    ],
    'balisehtml' => [
        'title' => 'Les balises HTML — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'Les balises HTML',
        'subtitle' => 'Exercices de structure HTML.',
        'summary' => 'Exploration des balises HTML et de la structuration de contenu.',
        'parentPageSlug' => 'faculte',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
        ],
    ],
    'experience' => [
        'title' => 'Assistant de Conduite — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'Assistant de Conduite',
        'subtitle' => 'Mini-projet interactif en JavaScript.',
        'summary' => 'Assistant d\'experience de conduite realise en HTML, CSS et JavaScript.',
        'parentPageSlug' => 'faculte',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'blue', 'label' => 'JavaScript'],
        ],
    ],
    'fizzbuzz' => [
        'title' => 'FizzBuzz — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'FizzBuzz',
        'subtitle' => 'Premier exercice de logique en C.',
        'summary' => 'Programme FizzBuzz en C pour pratiquer les conditions et les boucles.',
        'parentPageSlug' => 'faculte',
        'tags' => [
            ['class' => 'amber', 'label' => 'C'],
        ],
    ],
    'mastermind' => [
        'title' => 'Mastermind — Justine Hannauer',
        'badge' => 'Première année',
        'heading' => 'Mastermind',
        'subtitle' => 'Jeu de logique en C.',
        'summary' => 'Projet Mastermind en C pour travailler les algorithmes et la logique.',
        'parentPageSlug' => 'faculte',
        'tags' => [
            ['class' => 'amber', 'label' => 'C'],
        ],
    ],
    'vitrine' => [
        'title' => 'Illustrations et Maquettes — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Illustrations et Maquettes',
        'subtitle' => 'InDesign, Illustrator et Figma',
        'summary' => 'Travaux de design visuel et maquettes desktop/mobile.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'green', 'label' => 'Figma'],
            ['class' => 'green', 'label' => 'InDesign'],
            ['class' => 'green', 'label' => 'Illustrator'],
        ],
    ],
    'htmlcover' => [
        'title' => 'Première utilisation de Bootstrap — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Première utilisation de Bootstrap',
        'subtitle' => 'Template one-page avec Bootstrap.',
        'summary' => 'Prise en main de Bootstrap avec une page de couverture responsive.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'purple', 'label' => 'Bootstrap'],
        ],
    ],
    'tutorat' => [
        'title' => 'Reproduction de maquette — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Reproduction d\'une maquette',
        'subtitle' => 'Integration HTML/CSS d\'une interface de restaurant.',
        'summary' => 'Mise en pratique des bases front avec une reproduction pixel-approchante.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'pink', 'label' => 'Figma'],
        ],
    ],
    'sae301' => [
        'title' => 'Projet SAE301 Clay — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Projet SAE301 Clay',
        'subtitle' => 'Site web pour la gestion d\'un projet d\'aviation.',
        'summary' => 'Projet Laravel de vente/achat d\'avions avec gestion utilisateurs.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'amber', 'label' => 'PHP'],
            ['class' => 'amber', 'label' => 'SQLite'],
            ['class' => 'purple', 'label' => 'Twig'],
            ['class' => 'green', 'label' => 'Figma'],
            ['class' => 'pink', 'label' => 'Methode Agile'],
            ['class' => 'pink', 'label' => 'Scrum'],
            ['class' => 'pink', 'label' => 'Trello'],
        ],
    ],
    'clay' => [
        'title' => 'Projet Clay Symfony — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Projet Clay',
        'subtitle' => 'Refonte Symfony du projet aviation.',
        'summary' => 'Refonte de SAE301 avec Symfony et optimisation du parcours utilisateur.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'amber', 'label' => 'SQLite'],
            ['class' => 'purple', 'label' => 'Symfony'],
            ['class' => 'purple', 'label' => 'Twig'],
        ],
    ],
    'sae401' => [
        'title' => 'Projet SAE401 Decrypt\'eau — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Projet SAE401',
        'subtitle' => 'Jeu éducatif sur le cycle de l\'eau.',
        'summary' => 'Projet Symfony/JavaScript de jeu sérieux avec cartes et mécaniques pédagogiques.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'blue', 'label' => 'JavaScript'],
            ['class' => 'amber', 'label' => 'MySQL'],
            ['class' => 'purple', 'label' => 'Symfony'],
            ['class' => 'purple', 'label' => 'Twig'],
            ['class' => 'green', 'label' => 'Figma'],
            ['class' => 'pink', 'label' => 'Methode Agile'],
            ['class' => 'pink', 'label' => 'Scrum'],
            ['class' => 'pink', 'label' => 'Trello'],
        ],
    ],
    'sae402' => [
        'title' => 'Projet SAE402 — Justine Hannauer',
        'badge' => 'Deuxième année BUT',
        'heading' => 'Projet SAE402',
        'subtitle' => 'Jeu vidéo Unity avec assets Blender.',
        'summary' => 'Conception d\'une scene de jeu et intégration 3D/logicielle.',
        'parentPageSlug' => 'deuxieme',
        'tags' => [
            ['class' => 'teal', 'label' => 'Unity'],
            ['class' => 'green', 'label' => 'Blender'],
            ['class' => 'amber', 'label' => 'C#'],
            ['class' => 'pink', 'label' => 'Methode Agile'],
        ],
    ],
    'accessibilite' => [
        'title' => 'Site web accessible — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Site web accessible',
        'subtitle' => 'Conception d\'interfaces accessibles selon les normes WCAG.',
        'summary' => 'Projet de création d\'un site accessible avec approche UX et gestion agile.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'purple', 'label' => 'Tailwind CSS'],
            ['class' => 'pink', 'label' => 'Accessibilité'],
            ['class' => 'pink', 'label' => 'Gestion de projet'],
            ['class' => 'pink', 'label' => 'Trello'],
        ],
    ],
    'jirlo' => [
        'title' => 'Projet Jirlo — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Projet Jirlo',
        'subtitle' => 'Application de gestion agile developpée avec Laravel.',
        'summary' => 'Mise en place de sprints, user stories et tableau de bord projet.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'amber', 'label' => 'SQLite'],
            ['class' => 'purple', 'label' => 'Laravel'],
            ['class' => 'purple', 'label' => 'Tailwind CSS'],
            ['class' => 'green', 'label' => 'Figma'],
            ['class' => 'pink', 'label' => 'Trello'],
            ['class' => 'pink', 'label' => 'Miro'],
            ['class' => 'pink', 'label' => 'Cahier des charges'],
        ],
    ],
    'chocolat' => [
        'title' => 'L\'Usine Chocolat — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'L\'Usine Chocolat',
        'subtitle' => 'Application web métier autour d\'un cas d\'usine.',
        'summary' => 'Projet Laravel avec organisation agile et pilotage produit.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'amber', 'label' => 'SQLite'],
            ['class' => 'purple', 'label' => 'Laravel'],
            ['class' => 'purple', 'label' => 'Tailwind CSS'],
            ['class' => 'green', 'label' => 'Figma'],
            ['class' => 'pink', 'label' => 'Agile'],
            ['class' => 'pink', 'label' => 'Trello'],
            ['class' => 'pink', 'label' => 'Cahier des charges'],
            ['class' => 'pink', 'label' => 'Miro'],
        ],
    ],
    'di5' => [
        'title' => 'Application mobile — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Application mobile',
        'subtitle' => 'Application Android de recherche de cinémas et films.',
        'summary' => 'Prototype mobile avec parcours utilisateur et billetterie.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'teal', 'label' => 'Android Studio'],
            ['class' => 'amber', 'label' => 'Kotlin'],
        ],
    ],
    'visu' => [
        'title' => 'Projet visualisation 3D — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Projet visualisation 3D',
        'subtitle' => 'Visualisation 3D autour d\'un musée d\'art.',
        'summary' => 'Scene 3D interactive pour valoriser des contenus culturels.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'JavaScript'],
            ['class' => 'purple', 'label' => 'Three.js'],
            ['class' => 'coral', 'label' => '3D'],
        ],
    ],
    'ad' => [
        'title' => 'Refonte Alsace Digitale — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Refonte du site d\'Alsace Digitale',
        'subtitle' => 'Site vitrine pour évènements, communauté et activites.',
        'summary' => 'Refonte orientee contenus et lisibilite avec approche agile.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'amber', 'label' => 'Strapi'],
            ['class' => 'purple', 'label' => 'VueJS'],
            ['class' => 'purple', 'label' => 'NuxtJS'],
            ['class' => 'pink', 'label' => 'Scrum'],
            ['class' => 'pink', 'label' => 'Trello'],
        ],
    ],
    'spa' => [
        'title' => 'Refonte SPA Strasbourg — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Refonte du site de la SPA Strasbourg',
        'subtitle' => 'Amélioration de l\'information, adoption et benévolat.',
        'summary' => 'Refonte UX/UI avec contenus clarifies et dispositif de communication.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'blue', 'label' => 'HTML'],
            ['class' => 'blue', 'label' => 'CSS'],
            ['class' => 'blue', 'label' => 'JavaScript'],
            ['class' => 'amber', 'label' => 'PHP'],
            ['class' => 'orange', 'label' => 'WordPress'],
            ['class' => 'pink', 'label' => 'Miro'],
            ['class' => 'pink', 'label' => 'Trello'],
            ['class' => 'pink', 'label' => 'Cahier des charges'],
            ['class' => 'green', 'label' => 'Figma'],
            ['class' => 'green', 'label' => 'Canva'],
            ['class' => 'green', 'label' => 'DaVinci Resolve'],
        ],
    ],
    'di6' => [
        'title' => 'Projets Unity et IA — Justine Hannauer',
        'badge' => 'Troisième année BUT',
        'heading' => 'Projets Unity et IA',
        'subtitle' => 'Jeux, VR/AR et expérimentation en IA génerative.',
        'summary' => 'Serie de prototypes techniques autour du gameplay et de l\'interactivite.',
        'parentPageSlug' => 'troisieme',
        'tags' => [
            ['class' => 'teal', 'label' => 'Unity'],
            ['class' => 'amber', 'label' => 'C#'],
            ['class' => 'amber', 'label' => 'Python'],
            ['class' => 'coral', 'label' => 'Réalite virtuelle'],
            ['class' => 'coral', 'label' => 'Réalite augmentee'],
            ['class' => 'coral', 'label' => 'IA generative'],
            ['class' => 'coral', 'label' => '3D'],
        ],
    ],
];
